/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wfB8Myw9y5G
 */
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import Image from "next/image";

export function MusicSearchComponent() {
  return (
    <>
      <header className="flex items-center justify-between p-4 w-full bg-green-600">
        <h1 className="text-white p-12">Spotify Song Recommendations</h1>
        <input
          className="p-2 rounded-lg"
          placeholder="Search songs..."
          type="text"
        />
      </header>
      <main className="p-4 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card className="bg-white rounded-lg shadow-md">
          <CardHeader className="p-4">
            <h2 className="font-semibold">Song Title 1</h2>
          </CardHeader>
          <CardContent className="p-4">
            <p className="mb-4">Artist Name 1</p>
            <Image
              alt="Album cover"
              className="w-full object-cover h-[200px] mb-4 rounded-lg"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <Button className="bg-green-500 hover:bg-green-600 text-white rounded-lg p-2">
              Play
            </Button>
          </CardContent>
        </Card>
        <Card className="bg-white rounded-lg shadow-md">
          <CardHeader className="p-4">
            <h2 className="font-semibold">Song Title 2</h2>
          </CardHeader>
          <CardContent className="p-4">
            <p className="mb-4">Artist Name 2</p>
            <img
              alt="Album cover"
              className="w-full object-cover h-[200px] mb-4 rounded-lg"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <Button className="bg-green-500 hover:bg-green-600 text-white rounded-lg p-2">
              Play
            </Button>
          </CardContent>
        </Card>
        <Card className="bg-white rounded-lg shadow-md">
          <CardHeader className="p-4">
            <h2 className="font-semibold">Song Title 3</h2>
          </CardHeader>
          <CardContent className="p-4">
            <p className="mb-4">Artist Name 3</p>
            <img
              alt="Album cover"
              className="w-full object-cover h-[200px] mb-4 rounded-lg"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <Button className="bg-green-500 hover:bg-green-600 text-white rounded-lg p-2">
              Play
            </Button>
          </CardContent>
        </Card>
      </main>
    </>
  );
}
